services:
  analytics-service:
    image: analytics-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_patient_event_type_container:3306/patient_event_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-service.kafka-service.orb.local:9092
    depends_on:
      - mysql
    networks:
      - internal


  mysql:
    image: mysql:latest
    container_name: mysql_patient_event_type_container
    environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: patient_event_db
    ports:
      - "3308:3306"
    networks:
      - internal
    volumes:
      - /Users/babacarthiam/Developer/db_volumes/analytics-service-db:/var/lib/mysql

networks:
  internal:
    driver: bridge

volumes:
  mysql_data:
    driver: local