services:
  auth-service:
    image: auth-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_auth_service_container:3306/authdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=Ih0jhKVcWGSCp3xbayjU2Z96kRMD8pnWem8TslJVmJg=
    depends_on:
      - mysql
    networks:
      - internal

  mysql:
    image: mysql:latest
    container_name: mysql_auth_service_container
    environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: authdb
    ports:
      - "3309:3306"
    networks:
      - internal
    volumes:
      - /Users/babacarthiam/Developer/db_volumes/auth-service-db:/var/lib/mysql

networks:
  internal:
    driver: bridge

volumes:
  mysql_data:
    driver: local