services:
  billing-service:
    image: billing-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_billing_request_container:3306/billing_request_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql
    networks:
      - internal

  mysql:
    image: mysql:latest
    container_name: mysql_billing_request_container
    environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: billing_request_db
    ports:
      - "3307:3306"
    networks:
      - internal
    volumes:
      - /Users/babacarthiam/Developer/db_volumes/billing-service-db:/var/lib/mysql

networks:
  internal:
    driver: bridge

volumes:
  mysql_data:
    driver: local